# GTNH 默认模组配置：每行填写一个模组英文名，# 开头为注释。
NeverEnoughCharacters-Rework
MouseSideButtonFix
WorldEdit
OmniOcular
NEI-RecipeTree
Applied Cooking
JdkJarVersion21Enforcer
Smooth Font
Qz-UILib
FPS Reducer
Lag Goggles: Legacy
Mineshot
Twist Space Technology Mod
Programmable Hatch Mod
EZNuclear
EZMiner
WildcardPattern
GT-Simple-Wireless-Network
GT-Steam-Reborn
AE2InfinityCell
Advanced Memory Card
Brandons Core
WorldEdit CUI
